[colors.primary]
background = "#242936"
foreground = "#cccac2"

[colors.normal]
black = "#1a1f29"
blue = "#73d0ff"
cyan = "#51e3e3"
green = "#d5ff80"
magenta = "#dfbfff"
red = "#f28779"
white = "#cccac2"
yellow = "#ffcc77"

[font]
size = 10
offset = { x = 0, y = 3 }

[keyboard]
bindings = [
  {key = "W", mods = "Control|Shift", action = "Quit"}
]

[window]
# decorations = "None"
title = ""
dynamic_title = false
opacity = 0.99
padding = { x = 2, y = 2 }
