[window]
padding = { x = 0, y = 0 }
opacity = 0.99

[font]
size = 10
offset = { x = 0, y = 3 }

[colors.primary]
background = "#242936"
foreground = "#cccac2"

[colors.normal]
black = "#1a1f29"
blue = "#73d0ff"
cyan = "#51e3e3"
green = "#d5ff80"
magenta = "#dfbfff"
red = "#f28779"
white = "#cccac2"
yellow = "#ffcc77"
