# in windows under c/Users/<user_name>/AppData/Roaming/alacritty

# Colors (Ayu Mirage)
# Default Colors
[colors.primary]
background = "#1f2430"
foreground = "#cbccc6"
bright_foreground = "#f28779"

# Normal colors
[colors.normal]
black = "#212733"
red = "#f08778"
green = "#53bf97"
yellow = "#fdcc60"
blue = "#60b8d6"
magenta = "#ec7171"
cyan = "#98e6ca"
white = "#fafafa"

# Bright colors
[colors.bright]
black = "#686868"
red = "#f58c7d"
green = "#58c49c"
yellow = "#ffd165"
blue = "#65bddb"
magenta = "#f17676"
cyan = "#9debcf"
white = "#ffffff"

[font]
size = 10
offset = { x = 0, y = 3 }

[keyboard]
bindings = [
  {key = "W", mods = "Control|Shift", action = "Quit"}
]

[window]
# decorations = "None"
title = ""
dynamic_title = false
opacity = 0.96
padding = { x = 2, y = 2 }
