# using ANSI colors: https://i.stack.imgur.com/KTSQa.png

# Use custom format
# format = '''
# [┌───>](bold green)$all
# [└─>](bold green) '''

# prompt format
# format = "$all"
# right_format = """$username$hostname$time"""
format = "$directory$character"
right_format = "$all"

# Inserts a blank line between shell prompts
add_newline = false

[aws]
symbol = "aws: "
format = ' [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = 'fg:#565B66'

[character]
success_symbol = "[❯](bold fg:#D5FF80)"
error_symbol = "[❯](bold fg:#F28779)"
vimcmd_symbol = "[❮](bold fg:#76BCBC)"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:#717884"

[conda]
symbol = ""
style ="fg:#565B66"
format = "[$symbol$environment]($style) "

[directory]
truncation_length = 1
truncation_symbol = " /"
style = "fg:#565B66"
read_only = " [x]"

[git_branch]
symbol = "g: "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "fg:#565B66"

[git_commit]
tag_symbol = "tag "

[git_status]
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:#FFAD66) ($ahead_behind$stashed)]($style) "
style = "fg:#565B66"

[hostname]
disabled = true

[line_break]
disabled = true

[python]
format = '[(\($virtualenv\))]($style) '
symbol = "py "
style = "fg:#565B66"

[rust]
symbol = "rs "
format = '[$symbol($version )]($style)'
style = "fg:#565B66"

[time]
disabled = false
format = '[$time]($style) '
time_format = "%R"
style = "fg:#565B66"

[username]
disabled = true

# ------------------------
# removing further symbols
[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "pkg "
disabled = true

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "trfrm "

[zig]
symbol = "zig "
