# using ANSI colors: https://i.stack.imgur.com/KTSQa.png

# Use custom format
# format = '''
# [┌───>](bold green)$all
# [└─>](bold green) '''

# prompt format
# format = "$all"
# right_format = """$username$hostname$time"""
format = "$directory$character"
right_format = "$all"

# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[>](bold fg:#76BCBC)"
error_symbol = "[x](bold fg:#C86770)"
vimcmd_symbol = "[<](bold fg:#76BCBC)"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:#717884"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "fg:#EBEBEB"
read_only = " [x]"

[git_branch]
symbol = "g: "
format = '[ | $symbol$branch(:$remote_branch)]($style)'
# style = "fg:#D6B077"
style = "fg:#717884"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
format = '( [\[$all_status$ahead_behind\]]($style))'
# style = "fg:#76BCBC"
style = "fg:#717884"

[hostname]
disabled = false
ssh_only = false
format = '[$hostname]($style)'
style = "fg:#717884"

[line_break]
disabled = true

[python]
format = '[ | ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
symbol = "py "
style = "fg:#717884"

[time]
disabled = false
format = '[ | $time]($style) '
style = "fg:#717884"

[username]
disabled = false
show_always = true
format = '[$user@]($style)'
style_user = "fg:#717884"

# ------------------------
# removing further symbols
[aws]
symbol = "aws "
disabled = true

[azure]
symbol = "az "

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = ""
style ="fg:#717884"
format = "[@ $symbol$environment]($style) "
[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = "pkg "
disabled = true

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[solidity]
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "trfrm "

[zig]
symbol = "zig "
