# using ANSI colors: https://i.stack.imgur.com/KTSQa.png

# Use custom format
# format = '''
# [┌───>](bold green)$all
# [└─>](bold green) '''

# prompt format
# format = "$all"
# right_format = """$username$hostname$time"""
format = "$directory$character"
right_format = "$all"

# Inserts a blank line between shell prompts
add_newline = false

command_timeout = 3000

[aws]
symbol = "aws: "
format = ' [$symbol($profile )(\[$duration\] )]($style)'
style = 'fg:#565B66'

[character]
success_symbol = "[❯](bold fg:#D5FF80)"
error_symbol = "[❯](bold fg:#F28779)"
vimcmd_symbol = "[❮](bold fg:#76BCBC)"

[cmd_duration]
min_time = 5000
format = "[t: $duration]($style) "
style = "fg:#686868"

[conda]
symbol = ""
style ="fg:#686868"
format = "[$symbol$environment]($style) "

[directory]
truncation_length = 1
truncation_symbol = " /"
style = "fg:#686868"
read_only = " [x]"

[git_branch]
symbol = "g: "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "fg:#686868"

[git_commit]
tag_symbol = "tag "

[git_status]
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:#FFAD66) ($ahead_behind$stashed)]($style) "
style = "fg:#686868"

[hostname]
disabled = true

[line_break]
disabled = true

[python]
format = '[(\($virtualenv\))]($style) '
symbol = "py "
style = "fg:#686868"

[rust]
symbol = "rs "
format = '[$symbol($version )]($style)'
style = "fg:#686868"

[time]
disabled = false
format = '[$time]($style) '
time_format = "%R"
style = "fg:#686868"

[username]
disabled = true

[package]
disabled = true
